
ifneq ($(filter raphael,$(TARGET_DEVICE)),)

KERNEL_OUT := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/
KERNEL_HEADERS_INSTALL := $(KERNEL_OUT)/usr

$(KERNEL_OUT):
	mkdir -p $(KERNEL_OUT)

$(KERNEL_HEADERS_INSTALL): $(KERNEL_OUT)
	cp -Rf $(LOCAL_PATH)/headers/$(TARGET_DEVICE)/kernel_headers $(KERNEL_HEADERS_INSTALL)

endif